package Snowflakes;

public enum SnowflakeType {

    SNOWFLAKE_TYPE_ONE,
    SNOWFLAKE_TYPE_TWO,
    SNOWFLAKE_TYPE_THREE,
    SNOWFLAKE_TYPE_FOUR,
    SNOWFLAKE_TYPE_FIVE,
    SNOWFLAKE_TYPE_SIX,
    SNOWFLAKE_TYPE_SEVEN,
    SNOWFLAKE_TYPE_EIGHT,
    SNOWFLAKE_TYPE_NINE,
    SNOWFLAKE_TYPE_TEN,
    SNOWFLAKE_TYPE_ELEVEN,
    SNOWFLAKE_TYPE_TWELVE,
    SNOWFLAKE_TYPE_THIRTEEN,
    SNOWFLAKE_TYPE_FOURTEEN,
    SNOWFLAKE_TYPE_FIFTEEN
}
