public enum SnowflakeType {

    SNOWFLAKE_TYPE_ONE,
    SNOWFLAKE_TYPE_TWO,
    SNOWFLAKE_TYPE_THREE,
    SNOWFLAKE_TYPE_FOUR,
    SNOWFLAKE_TYPE_FIVE,
    SNOWFLAKE_TYPE_SIX,
    SNOWFLAKE_TYPE_SEVEN,
    SNOWFLAKE_TYPE_EIGHT
}
